/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.ach.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.ach.JSON;

/**
 * Addenda99Dishonored
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T08:19:26.833252621Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class Addenda99Dishonored {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TYPE_CODE = "typeCode";
  @SerializedName(SERIALIZED_NAME_TYPE_CODE)
  @javax.annotation.Nonnull
  private String typeCode;

  public static final String SERIALIZED_NAME_ORIGINAL_ENTRY_TRACE_NUMBER = "originalEntryTraceNumber";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_ENTRY_TRACE_NUMBER)
  @javax.annotation.Nonnull
  private String originalEntryTraceNumber;

  public static final String SERIALIZED_NAME_ORIGINAL_RECEIVING_D_F_I_IDENTIFICATION = "originalReceivingDFIIdentification";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_RECEIVING_D_F_I_IDENTIFICATION)
  @javax.annotation.Nonnull
  private String originalReceivingDFIIdentification;

  public static final String SERIALIZED_NAME_RETURN_TRACE_NUMBER = "returnTraceNumber";
  @SerializedName(SERIALIZED_NAME_RETURN_TRACE_NUMBER)
  @javax.annotation.Nonnull
  private String returnTraceNumber;

  public static final String SERIALIZED_NAME_RETURN_SETTLEMENT_DATE = "returnSettlementDate";
  @SerializedName(SERIALIZED_NAME_RETURN_SETTLEMENT_DATE)
  @javax.annotation.Nonnull
  private String returnSettlementDate;

  public static final String SERIALIZED_NAME_RETURN_REASON_CODE = "returnReasonCode";
  @SerializedName(SERIALIZED_NAME_RETURN_REASON_CODE)
  @javax.annotation.Nonnull
  private String returnReasonCode;

  public static final String SERIALIZED_NAME_DISHONORED_RETURN_REASON_CODE = "dishonoredReturnReasonCode";
  @SerializedName(SERIALIZED_NAME_DISHONORED_RETURN_REASON_CODE)
  @javax.annotation.Nonnull
  private String dishonoredReturnReasonCode;

  public static final String SERIALIZED_NAME_TRACE_NUMBER = "traceNumber";
  @SerializedName(SERIALIZED_NAME_TRACE_NUMBER)
  @javax.annotation.Nullable
  private String traceNumber;

  public static final String SERIALIZED_NAME_ADDENDA_INFORMATION = "addendaInformation";
  @SerializedName(SERIALIZED_NAME_ADDENDA_INFORMATION)
  @javax.annotation.Nullable
  private String addendaInformation;

  public static final String SERIALIZED_NAME_LINE_NUMBER = "lineNumber";
  @SerializedName(SERIALIZED_NAME_LINE_NUMBER)
  @javax.annotation.Nullable
  private Integer lineNumber;

  public Addenda99Dishonored() {
  }

  public Addenda99Dishonored id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Client-defined string used as a reference to this record.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Addenda99Dishonored typeCode(@javax.annotation.Nonnull String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

  /**
   * 99 - NACHA regulations
   * @return typeCode
   */
  @javax.annotation.Nonnull
  public String getTypeCode() {
    return typeCode;
  }

  public void setTypeCode(@javax.annotation.Nonnull String typeCode) {
    this.typeCode = typeCode;
  }


  public Addenda99Dishonored originalEntryTraceNumber(@javax.annotation.Nonnull String originalEntryTraceNumber) {
    this.originalEntryTraceNumber = originalEntryTraceNumber;
    return this;
  }

  /**
   * Trace Number of the original entry being returned.
   * @return originalEntryTraceNumber
   */
  @javax.annotation.Nonnull
  public String getOriginalEntryTraceNumber() {
    return originalEntryTraceNumber;
  }

  public void setOriginalEntryTraceNumber(@javax.annotation.Nonnull String originalEntryTraceNumber) {
    this.originalEntryTraceNumber = originalEntryTraceNumber;
  }


  public Addenda99Dishonored originalReceivingDFIIdentification(@javax.annotation.Nonnull String originalReceivingDFIIdentification) {
    this.originalReceivingDFIIdentification = originalReceivingDFIIdentification;
    return this;
  }

  /**
   * Identification of the Original Receiving Depository Institution (ODFI)
   * @return originalReceivingDFIIdentification
   */
  @javax.annotation.Nonnull
  public String getOriginalReceivingDFIIdentification() {
    return originalReceivingDFIIdentification;
  }

  public void setOriginalReceivingDFIIdentification(@javax.annotation.Nonnull String originalReceivingDFIIdentification) {
    this.originalReceivingDFIIdentification = originalReceivingDFIIdentification;
  }


  public Addenda99Dishonored returnTraceNumber(@javax.annotation.Nonnull String returnTraceNumber) {
    this.returnTraceNumber = returnTraceNumber;
    return this;
  }

  /**
   * Return trace number
   * @return returnTraceNumber
   */
  @javax.annotation.Nonnull
  public String getReturnTraceNumber() {
    return returnTraceNumber;
  }

  public void setReturnTraceNumber(@javax.annotation.Nonnull String returnTraceNumber) {
    this.returnTraceNumber = returnTraceNumber;
  }


  public Addenda99Dishonored returnSettlementDate(@javax.annotation.Nonnull String returnSettlementDate) {
    this.returnSettlementDate = returnSettlementDate;
    return this;
  }

  /**
   * Return settlement date
   * @return returnSettlementDate
   */
  @javax.annotation.Nonnull
  public String getReturnSettlementDate() {
    return returnSettlementDate;
  }

  public void setReturnSettlementDate(@javax.annotation.Nonnull String returnSettlementDate) {
    this.returnSettlementDate = returnSettlementDate;
  }


  public Addenda99Dishonored returnReasonCode(@javax.annotation.Nonnull String returnReasonCode) {
    this.returnReasonCode = returnReasonCode;
    return this;
  }

  /**
   * Return reason code
   * @return returnReasonCode
   */
  @javax.annotation.Nonnull
  public String getReturnReasonCode() {
    return returnReasonCode;
  }

  public void setReturnReasonCode(@javax.annotation.Nonnull String returnReasonCode) {
    this.returnReasonCode = returnReasonCode;
  }


  public Addenda99Dishonored dishonoredReturnReasonCode(@javax.annotation.Nonnull String dishonoredReturnReasonCode) {
    this.dishonoredReturnReasonCode = dishonoredReturnReasonCode;
    return this;
  }

  /**
   * Return reason code of the Dishonored Return
   * @return dishonoredReturnReasonCode
   */
  @javax.annotation.Nonnull
  public String getDishonoredReturnReasonCode() {
    return dishonoredReturnReasonCode;
  }

  public void setDishonoredReturnReasonCode(@javax.annotation.Nonnull String dishonoredReturnReasonCode) {
    this.dishonoredReturnReasonCode = dishonoredReturnReasonCode;
  }


  public Addenda99Dishonored traceNumber(@javax.annotation.Nullable String traceNumber) {
    this.traceNumber = traceNumber;
    return this;
  }

  /**
   * Matches the Entry Detail Trace Number of the entry being returned.
   * @return traceNumber
   */
  @javax.annotation.Nullable
  public String getTraceNumber() {
    return traceNumber;
  }

  public void setTraceNumber(@javax.annotation.Nullable String traceNumber) {
    this.traceNumber = traceNumber;
  }


  public Addenda99Dishonored addendaInformation(@javax.annotation.Nullable String addendaInformation) {
    this.addendaInformation = addendaInformation;
    return this;
  }

  /**
   * Additional data
   * @return addendaInformation
   */
  @javax.annotation.Nullable
  public String getAddendaInformation() {
    return addendaInformation;
  }

  public void setAddendaInformation(@javax.annotation.Nullable String addendaInformation) {
    this.addendaInformation = addendaInformation;
  }


  public Addenda99Dishonored lineNumber(@javax.annotation.Nullable Integer lineNumber) {
    this.lineNumber = lineNumber;
    return this;
  }

  /**
   * Line number at which the record appears in the file.
   * @return lineNumber
   */
  @javax.annotation.Nullable
  public Integer getLineNumber() {
    return lineNumber;
  }

  public void setLineNumber(@javax.annotation.Nullable Integer lineNumber) {
    this.lineNumber = lineNumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Addenda99Dishonored addenda99Dishonored = (Addenda99Dishonored) o;
    return Objects.equals(this.id, addenda99Dishonored.id) &&
        Objects.equals(this.typeCode, addenda99Dishonored.typeCode) &&
        Objects.equals(this.originalEntryTraceNumber, addenda99Dishonored.originalEntryTraceNumber) &&
        Objects.equals(this.originalReceivingDFIIdentification, addenda99Dishonored.originalReceivingDFIIdentification) &&
        Objects.equals(this.returnTraceNumber, addenda99Dishonored.returnTraceNumber) &&
        Objects.equals(this.returnSettlementDate, addenda99Dishonored.returnSettlementDate) &&
        Objects.equals(this.returnReasonCode, addenda99Dishonored.returnReasonCode) &&
        Objects.equals(this.dishonoredReturnReasonCode, addenda99Dishonored.dishonoredReturnReasonCode) &&
        Objects.equals(this.traceNumber, addenda99Dishonored.traceNumber) &&
        Objects.equals(this.addendaInformation, addenda99Dishonored.addendaInformation) &&
        Objects.equals(this.lineNumber, addenda99Dishonored.lineNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, typeCode, originalEntryTraceNumber, originalReceivingDFIIdentification, returnTraceNumber, returnSettlementDate, returnReasonCode, dishonoredReturnReasonCode, traceNumber, addendaInformation, lineNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Addenda99Dishonored {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    originalEntryTraceNumber: ").append(toIndentedString(originalEntryTraceNumber)).append("\n");
    sb.append("    originalReceivingDFIIdentification: ").append(toIndentedString(originalReceivingDFIIdentification)).append("\n");
    sb.append("    returnTraceNumber: ").append(toIndentedString(returnTraceNumber)).append("\n");
    sb.append("    returnSettlementDate: ").append(toIndentedString(returnSettlementDate)).append("\n");
    sb.append("    returnReasonCode: ").append(toIndentedString(returnReasonCode)).append("\n");
    sb.append("    dishonoredReturnReasonCode: ").append(toIndentedString(dishonoredReturnReasonCode)).append("\n");
    sb.append("    traceNumber: ").append(toIndentedString(traceNumber)).append("\n");
    sb.append("    addendaInformation: ").append(toIndentedString(addendaInformation)).append("\n");
    sb.append("    lineNumber: ").append(toIndentedString(lineNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "typeCode", "originalEntryTraceNumber", "originalReceivingDFIIdentification", "returnTraceNumber", "returnSettlementDate", "returnReasonCode", "dishonoredReturnReasonCode", "traceNumber", "addendaInformation", "lineNumber"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("typeCode", "originalEntryTraceNumber", "originalReceivingDFIIdentification", "returnTraceNumber", "returnSettlementDate", "returnReasonCode", "dishonoredReturnReasonCode"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Addenda99Dishonored
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Addenda99Dishonored.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Addenda99Dishonored is not found in the empty JSON string", Addenda99Dishonored.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Addenda99Dishonored.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Addenda99Dishonored` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Addenda99Dishonored.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("typeCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `typeCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("typeCode").toString()));
      }
      if (!jsonObj.get("originalEntryTraceNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `originalEntryTraceNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originalEntryTraceNumber").toString()));
      }
      if (!jsonObj.get("originalReceivingDFIIdentification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `originalReceivingDFIIdentification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originalReceivingDFIIdentification").toString()));
      }
      if (!jsonObj.get("returnTraceNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `returnTraceNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("returnTraceNumber").toString()));
      }
      if (!jsonObj.get("returnSettlementDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `returnSettlementDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("returnSettlementDate").toString()));
      }
      if (!jsonObj.get("returnReasonCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `returnReasonCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("returnReasonCode").toString()));
      }
      if (!jsonObj.get("dishonoredReturnReasonCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dishonoredReturnReasonCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dishonoredReturnReasonCode").toString()));
      }
      if ((jsonObj.get("traceNumber") != null && !jsonObj.get("traceNumber").isJsonNull()) && !jsonObj.get("traceNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traceNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traceNumber").toString()));
      }
      if ((jsonObj.get("addendaInformation") != null && !jsonObj.get("addendaInformation").isJsonNull()) && !jsonObj.get("addendaInformation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addendaInformation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addendaInformation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Addenda99Dishonored.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Addenda99Dishonored' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Addenda99Dishonored> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Addenda99Dishonored.class));

       return (TypeAdapter<T>) new TypeAdapter<Addenda99Dishonored>() {
           @Override
           public void write(JsonWriter out, Addenda99Dishonored value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Addenda99Dishonored read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Addenda99Dishonored given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Addenda99Dishonored
   * @throws IOException if the JSON string is invalid with respect to Addenda99Dishonored
   */
  public static Addenda99Dishonored fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Addenda99Dishonored.class);
  }

  /**
   * Convert an instance of Addenda99Dishonored to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

