/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.ach.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.mifos.ach.model.ADVBatchControl;
import org.mifos.ach.model.ADVEntryDetail;
import org.mifos.ach.model.BatchControl;
import org.mifos.ach.model.BatchHeader;
import org.mifos.ach.model.EntryDetail;
import org.mifos.ach.model.Offset;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.ach.JSON;

/**
 * Batch
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T08:19:26.833252621Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class Batch {
  public static final String SERIALIZED_NAME_BATCH_HEADER = "batchHeader";
  @SerializedName(SERIALIZED_NAME_BATCH_HEADER)
  @javax.annotation.Nonnull
  private BatchHeader batchHeader;

  public static final String SERIALIZED_NAME_ENTRY_DETAILS = "entryDetails";
  @SerializedName(SERIALIZED_NAME_ENTRY_DETAILS)
  @javax.annotation.Nonnull
  private List<EntryDetail> entryDetails = new ArrayList<>();

  public static final String SERIALIZED_NAME_BATCH_CONTROL = "batchControl";
  @SerializedName(SERIALIZED_NAME_BATCH_CONTROL)
  @javax.annotation.Nullable
  private BatchControl batchControl;

  public static final String SERIALIZED_NAME_ADV_ENTRY_DETAILS = "advEntryDetails";
  @SerializedName(SERIALIZED_NAME_ADV_ENTRY_DETAILS)
  @javax.annotation.Nullable
  private List<ADVEntryDetail> advEntryDetails = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADV_BATCH_CONTROL = "advBatchControl";
  @SerializedName(SERIALIZED_NAME_ADV_BATCH_CONTROL)
  @javax.annotation.Nullable
  private ADVBatchControl advBatchControl;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  @javax.annotation.Nullable
  private Offset offset;

  public Batch() {
  }

  public Batch batchHeader(@javax.annotation.Nonnull BatchHeader batchHeader) {
    this.batchHeader = batchHeader;
    return this;
  }

  /**
   * Get batchHeader
   * @return batchHeader
   */
  @javax.annotation.Nonnull
  public BatchHeader getBatchHeader() {
    return batchHeader;
  }

  public void setBatchHeader(@javax.annotation.Nonnull BatchHeader batchHeader) {
    this.batchHeader = batchHeader;
  }


  public Batch entryDetails(@javax.annotation.Nonnull List<EntryDetail> entryDetails) {
    this.entryDetails = entryDetails;
    return this;
  }

  public Batch addEntryDetailsItem(EntryDetail entryDetailsItem) {
    if (this.entryDetails == null) {
      this.entryDetails = new ArrayList<>();
    }
    this.entryDetails.add(entryDetailsItem);
    return this;
  }

  /**
   * Get entryDetails
   * @return entryDetails
   */
  @javax.annotation.Nonnull
  public List<EntryDetail> getEntryDetails() {
    return entryDetails;
  }

  public void setEntryDetails(@javax.annotation.Nonnull List<EntryDetail> entryDetails) {
    this.entryDetails = entryDetails;
  }


  public Batch batchControl(@javax.annotation.Nullable BatchControl batchControl) {
    this.batchControl = batchControl;
    return this;
  }

  /**
   * Get batchControl
   * @return batchControl
   */
  @javax.annotation.Nullable
  public BatchControl getBatchControl() {
    return batchControl;
  }

  public void setBatchControl(@javax.annotation.Nullable BatchControl batchControl) {
    this.batchControl = batchControl;
  }


  public Batch advEntryDetails(@javax.annotation.Nullable List<ADVEntryDetail> advEntryDetails) {
    this.advEntryDetails = advEntryDetails;
    return this;
  }

  public Batch addAdvEntryDetailsItem(ADVEntryDetail advEntryDetailsItem) {
    if (this.advEntryDetails == null) {
      this.advEntryDetails = new ArrayList<>();
    }
    this.advEntryDetails.add(advEntryDetailsItem);
    return this;
  }

  /**
   * Get advEntryDetails
   * @return advEntryDetails
   */
  @javax.annotation.Nullable
  public List<ADVEntryDetail> getAdvEntryDetails() {
    return advEntryDetails;
  }

  public void setAdvEntryDetails(@javax.annotation.Nullable List<ADVEntryDetail> advEntryDetails) {
    this.advEntryDetails = advEntryDetails;
  }


  public Batch advBatchControl(@javax.annotation.Nullable ADVBatchControl advBatchControl) {
    this.advBatchControl = advBatchControl;
    return this;
  }

  /**
   * Get advBatchControl
   * @return advBatchControl
   */
  @javax.annotation.Nullable
  public ADVBatchControl getAdvBatchControl() {
    return advBatchControl;
  }

  public void setAdvBatchControl(@javax.annotation.Nullable ADVBatchControl advBatchControl) {
    this.advBatchControl = advBatchControl;
  }


  public Batch offset(@javax.annotation.Nullable Offset offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Get offset
   * @return offset
   */
  @javax.annotation.Nullable
  public Offset getOffset() {
    return offset;
  }

  public void setOffset(@javax.annotation.Nullable Offset offset) {
    this.offset = offset;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Batch batch = (Batch) o;
    return Objects.equals(this.batchHeader, batch.batchHeader) &&
        Objects.equals(this.entryDetails, batch.entryDetails) &&
        Objects.equals(this.batchControl, batch.batchControl) &&
        Objects.equals(this.advEntryDetails, batch.advEntryDetails) &&
        Objects.equals(this.advBatchControl, batch.advBatchControl) &&
        Objects.equals(this.offset, batch.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchHeader, entryDetails, batchControl, advEntryDetails, advBatchControl, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Batch {\n");
    sb.append("    batchHeader: ").append(toIndentedString(batchHeader)).append("\n");
    sb.append("    entryDetails: ").append(toIndentedString(entryDetails)).append("\n");
    sb.append("    batchControl: ").append(toIndentedString(batchControl)).append("\n");
    sb.append("    advEntryDetails: ").append(toIndentedString(advEntryDetails)).append("\n");
    sb.append("    advBatchControl: ").append(toIndentedString(advBatchControl)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("batchHeader", "entryDetails", "batchControl", "advEntryDetails", "advBatchControl", "offset"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("batchHeader", "entryDetails"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Batch
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Batch.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Batch is not found in the empty JSON string", Batch.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Batch.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Batch` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Batch.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `batchHeader`
      BatchHeader.validateJsonElement(jsonObj.get("batchHeader"));
      // ensure the json data is an array
      if (!jsonObj.get("entryDetails").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `entryDetails` to be an array in the JSON string but got `%s`", jsonObj.get("entryDetails").toString()));
      }

      JsonArray jsonArrayentryDetails = jsonObj.getAsJsonArray("entryDetails");
      // validate the required field `entryDetails` (array)
      for (int i = 0; i < jsonArrayentryDetails.size(); i++) {
        EntryDetail.validateJsonElement(jsonArrayentryDetails.get(i));
      };
      // validate the optional field `batchControl`
      if (jsonObj.get("batchControl") != null && !jsonObj.get("batchControl").isJsonNull()) {
        BatchControl.validateJsonElement(jsonObj.get("batchControl"));
      }
      if (jsonObj.get("advEntryDetails") != null && !jsonObj.get("advEntryDetails").isJsonNull()) {
        JsonArray jsonArrayadvEntryDetails = jsonObj.getAsJsonArray("advEntryDetails");
        if (jsonArrayadvEntryDetails != null) {
          // ensure the json data is an array
          if (!jsonObj.get("advEntryDetails").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `advEntryDetails` to be an array in the JSON string but got `%s`", jsonObj.get("advEntryDetails").toString()));
          }

          // validate the optional field `advEntryDetails` (array)
          for (int i = 0; i < jsonArrayadvEntryDetails.size(); i++) {
            ADVEntryDetail.validateJsonElement(jsonArrayadvEntryDetails.get(i));
          };
        }
      }
      // validate the optional field `advBatchControl`
      if (jsonObj.get("advBatchControl") != null && !jsonObj.get("advBatchControl").isJsonNull()) {
        ADVBatchControl.validateJsonElement(jsonObj.get("advBatchControl"));
      }
      // validate the optional field `offset`
      if (jsonObj.get("offset") != null && !jsonObj.get("offset").isJsonNull()) {
        Offset.validateJsonElement(jsonObj.get("offset"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Batch.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Batch' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Batch> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Batch.class));

       return (TypeAdapter<T>) new TypeAdapter<Batch>() {
           @Override
           public void write(JsonWriter out, Batch value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Batch read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Batch given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Batch
   * @throws IOException if the JSON string is invalid with respect to Batch
   */
  public static Batch fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Batch.class);
  }

  /**
   * Convert an instance of Batch to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

