/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.ach.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.ach.JSON;

/**
 * MergeConditions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T08:19:26.833252621Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class MergeConditions {
  public static final String SERIALIZED_NAME_MAX_LINES = "maxLines";
  @SerializedName(SERIALIZED_NAME_MAX_LINES)
  @javax.annotation.Nullable
  private Integer maxLines;

  public static final String SERIALIZED_NAME_MAX_DOLLAR_AMOUNT = "maxDollarAmount";
  @SerializedName(SERIALIZED_NAME_MAX_DOLLAR_AMOUNT)
  @javax.annotation.Nullable
  private Integer maxDollarAmount;

  public MergeConditions() {
  }

  public MergeConditions maxLines(@javax.annotation.Nullable Integer maxLines) {
    this.maxLines = maxLines;
    return this;
  }

  /**
   * Maximum number of lines in a merged file.
   * @return maxLines
   */
  @javax.annotation.Nullable
  public Integer getMaxLines() {
    return maxLines;
  }

  public void setMaxLines(@javax.annotation.Nullable Integer maxLines) {
    this.maxLines = maxLines;
  }


  public MergeConditions maxDollarAmount(@javax.annotation.Nullable Integer maxDollarAmount) {
    this.maxDollarAmount = maxDollarAmount;
    return this;
  }

  /**
   * Maximum total dollar amount in a merged file.
   * @return maxDollarAmount
   */
  @javax.annotation.Nullable
  public Integer getMaxDollarAmount() {
    return maxDollarAmount;
  }

  public void setMaxDollarAmount(@javax.annotation.Nullable Integer maxDollarAmount) {
    this.maxDollarAmount = maxDollarAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeConditions mergeConditions = (MergeConditions) o;
    return Objects.equals(this.maxLines, mergeConditions.maxLines) &&
        Objects.equals(this.maxDollarAmount, mergeConditions.maxDollarAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxLines, maxDollarAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeConditions {\n");
    sb.append("    maxLines: ").append(toIndentedString(maxLines)).append("\n");
    sb.append("    maxDollarAmount: ").append(toIndentedString(maxDollarAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("maxLines", "maxDollarAmount"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MergeConditions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MergeConditions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MergeConditions is not found in the empty JSON string", MergeConditions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MergeConditions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MergeConditions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MergeConditions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MergeConditions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MergeConditions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MergeConditions.class));

       return (TypeAdapter<T>) new TypeAdapter<MergeConditions>() {
           @Override
           public void write(JsonWriter out, MergeConditions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MergeConditions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MergeConditions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MergeConditions
   * @throws IOException if the JSON string is invalid with respect to MergeConditions
   */
  public static MergeConditions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MergeConditions.class);
  }

  /**
   * Convert an instance of MergeConditions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

