/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.ach.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.mifos.ach.model.ADVFileControl;
import org.mifos.ach.model.Batch;
import org.mifos.ach.model.FileControl;
import org.mifos.ach.model.FileHeader;
import org.mifos.ach.model.IATBatch;
import org.mifos.ach.model.ValidateOpts;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.ach.JSON;

/**
 * ModelFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T08:19:26.833252621Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class ModelFile {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_FILE_HEADER = "fileHeader";
  @SerializedName(SERIALIZED_NAME_FILE_HEADER)
  @javax.annotation.Nonnull
  private FileHeader fileHeader;

  public static final String SERIALIZED_NAME_BATCHES = "batches";
  @SerializedName(SERIALIZED_NAME_BATCHES)
  @javax.annotation.Nullable
  private List<Batch> batches = new ArrayList<>();

  public static final String SERIALIZED_NAME_IA_T_BATCHES = "IATBatches";
  @SerializedName(SERIALIZED_NAME_IA_T_BATCHES)
  @javax.annotation.Nullable
  private List<IATBatch> iaTBatches = new ArrayList<>();

  public static final String SERIALIZED_NAME_FILE_CONTROL = "fileControl";
  @SerializedName(SERIALIZED_NAME_FILE_CONTROL)
  @javax.annotation.Nonnull
  private FileControl fileControl;

  public static final String SERIALIZED_NAME_NOTIFICATION_OF_CHANGE = "NotificationOfChange";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_OF_CHANGE)
  @javax.annotation.Nullable
  private List<Batch> notificationOfChange;

  public static final String SERIALIZED_NAME_RETURN_ENTRIES = "ReturnEntries";
  @SerializedName(SERIALIZED_NAME_RETURN_ENTRIES)
  @javax.annotation.Nullable
  private List<Batch> returnEntries;

  public static final String SERIALIZED_NAME_FILE_A_D_V_CONTROL = "fileADVControl";
  @SerializedName(SERIALIZED_NAME_FILE_A_D_V_CONTROL)
  @javax.annotation.Nullable
  private ADVFileControl fileADVControl;

  public static final String SERIALIZED_NAME_VALIDATE_OPTS = "validateOpts";
  @SerializedName(SERIALIZED_NAME_VALIDATE_OPTS)
  @javax.annotation.Nullable
  private ValidateOpts validateOpts;

  public ModelFile() {
  }

  public ModelFile id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * File ID
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ModelFile fileHeader(@javax.annotation.Nonnull FileHeader fileHeader) {
    this.fileHeader = fileHeader;
    return this;
  }

  /**
   * Get fileHeader
   * @return fileHeader
   */
  @javax.annotation.Nonnull
  public FileHeader getFileHeader() {
    return fileHeader;
  }

  public void setFileHeader(@javax.annotation.Nonnull FileHeader fileHeader) {
    this.fileHeader = fileHeader;
  }


  public ModelFile batches(@javax.annotation.Nullable List<Batch> batches) {
    this.batches = batches;
    return this;
  }

  public ModelFile addBatchesItem(Batch batchesItem) {
    if (this.batches == null) {
      this.batches = new ArrayList<>();
    }
    this.batches.add(batchesItem);
    return this;
  }

  /**
   * Get batches
   * @return batches
   */
  @javax.annotation.Nullable
  public List<Batch> getBatches() {
    return batches;
  }

  public void setBatches(@javax.annotation.Nullable List<Batch> batches) {
    this.batches = batches;
  }


  public ModelFile iaTBatches(@javax.annotation.Nullable List<IATBatch> iaTBatches) {
    this.iaTBatches = iaTBatches;
    return this;
  }

  public ModelFile addIaTBatchesItem(IATBatch iaTBatchesItem) {
    if (this.iaTBatches == null) {
      this.iaTBatches = new ArrayList<>();
    }
    this.iaTBatches.add(iaTBatchesItem);
    return this;
  }

  /**
   * Get iaTBatches
   * @return iaTBatches
   */
  @javax.annotation.Nullable
  public List<IATBatch> getIaTBatches() {
    return iaTBatches;
  }

  public void setIaTBatches(@javax.annotation.Nullable List<IATBatch> iaTBatches) {
    this.iaTBatches = iaTBatches;
  }


  public ModelFile fileControl(@javax.annotation.Nonnull FileControl fileControl) {
    this.fileControl = fileControl;
    return this;
  }

  /**
   * Get fileControl
   * @return fileControl
   */
  @javax.annotation.Nonnull
  public FileControl getFileControl() {
    return fileControl;
  }

  public void setFileControl(@javax.annotation.Nonnull FileControl fileControl) {
    this.fileControl = fileControl;
  }


  public ModelFile notificationOfChange(@javax.annotation.Nullable List<Batch> notificationOfChange) {
    this.notificationOfChange = notificationOfChange;
    return this;
  }

  public ModelFile addNotificationOfChangeItem(Batch notificationOfChangeItem) {
    if (this.notificationOfChange == null) {
      this.notificationOfChange = new ArrayList<>();
    }
    this.notificationOfChange.add(notificationOfChangeItem);
    return this;
  }

  /**
   * Get notificationOfChange
   * @return notificationOfChange
   */
  @javax.annotation.Nullable
  public List<Batch> getNotificationOfChange() {
    return notificationOfChange;
  }

  public void setNotificationOfChange(@javax.annotation.Nullable List<Batch> notificationOfChange) {
    this.notificationOfChange = notificationOfChange;
  }


  public ModelFile returnEntries(@javax.annotation.Nullable List<Batch> returnEntries) {
    this.returnEntries = returnEntries;
    return this;
  }

  public ModelFile addReturnEntriesItem(Batch returnEntriesItem) {
    if (this.returnEntries == null) {
      this.returnEntries = new ArrayList<>();
    }
    this.returnEntries.add(returnEntriesItem);
    return this;
  }

  /**
   * Get returnEntries
   * @return returnEntries
   */
  @javax.annotation.Nullable
  public List<Batch> getReturnEntries() {
    return returnEntries;
  }

  public void setReturnEntries(@javax.annotation.Nullable List<Batch> returnEntries) {
    this.returnEntries = returnEntries;
  }


  public ModelFile fileADVControl(@javax.annotation.Nullable ADVFileControl fileADVControl) {
    this.fileADVControl = fileADVControl;
    return this;
  }

  /**
   * Get fileADVControl
   * @return fileADVControl
   */
  @javax.annotation.Nullable
  public ADVFileControl getFileADVControl() {
    return fileADVControl;
  }

  public void setFileADVControl(@javax.annotation.Nullable ADVFileControl fileADVControl) {
    this.fileADVControl = fileADVControl;
  }


  public ModelFile validateOpts(@javax.annotation.Nullable ValidateOpts validateOpts) {
    this.validateOpts = validateOpts;
    return this;
  }

  /**
   * Get validateOpts
   * @return validateOpts
   */
  @javax.annotation.Nullable
  public ValidateOpts getValidateOpts() {
    return validateOpts;
  }

  public void setValidateOpts(@javax.annotation.Nullable ValidateOpts validateOpts) {
    this.validateOpts = validateOpts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelFile _file = (ModelFile) o;
    return Objects.equals(this.id, _file.id) &&
        Objects.equals(this.fileHeader, _file.fileHeader) &&
        Objects.equals(this.batches, _file.batches) &&
        Objects.equals(this.iaTBatches, _file.iaTBatches) &&
        Objects.equals(this.fileControl, _file.fileControl) &&
        Objects.equals(this.notificationOfChange, _file.notificationOfChange) &&
        Objects.equals(this.returnEntries, _file.returnEntries) &&
        Objects.equals(this.fileADVControl, _file.fileADVControl) &&
        Objects.equals(this.validateOpts, _file.validateOpts);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fileHeader, batches, iaTBatches, fileControl, notificationOfChange, returnEntries, fileADVControl, validateOpts);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelFile {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fileHeader: ").append(toIndentedString(fileHeader)).append("\n");
    sb.append("    batches: ").append(toIndentedString(batches)).append("\n");
    sb.append("    iaTBatches: ").append(toIndentedString(iaTBatches)).append("\n");
    sb.append("    fileControl: ").append(toIndentedString(fileControl)).append("\n");
    sb.append("    notificationOfChange: ").append(toIndentedString(notificationOfChange)).append("\n");
    sb.append("    returnEntries: ").append(toIndentedString(returnEntries)).append("\n");
    sb.append("    fileADVControl: ").append(toIndentedString(fileADVControl)).append("\n");
    sb.append("    validateOpts: ").append(toIndentedString(validateOpts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "fileHeader", "batches", "IATBatches", "fileControl", "NotificationOfChange", "ReturnEntries", "fileADVControl", "validateOpts"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("fileHeader", "fileControl"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModelFile
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModelFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModelFile is not found in the empty JSON string", ModelFile.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ModelFile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ModelFile` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ModelFile.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the required field `fileHeader`
      FileHeader.validateJsonElement(jsonObj.get("fileHeader"));
      if (jsonObj.get("batches") != null && !jsonObj.get("batches").isJsonNull()) {
        JsonArray jsonArraybatches = jsonObj.getAsJsonArray("batches");
        if (jsonArraybatches != null) {
          // ensure the json data is an array
          if (!jsonObj.get("batches").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `batches` to be an array in the JSON string but got `%s`", jsonObj.get("batches").toString()));
          }

          // validate the optional field `batches` (array)
          for (int i = 0; i < jsonArraybatches.size(); i++) {
            Batch.validateJsonElement(jsonArraybatches.get(i));
          };
        }
      }
      if (jsonObj.get("IATBatches") != null && !jsonObj.get("IATBatches").isJsonNull()) {
        JsonArray jsonArrayiaTBatches = jsonObj.getAsJsonArray("IATBatches");
        if (jsonArrayiaTBatches != null) {
          // ensure the json data is an array
          if (!jsonObj.get("IATBatches").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `IATBatches` to be an array in the JSON string but got `%s`", jsonObj.get("IATBatches").toString()));
          }

          // validate the optional field `IATBatches` (array)
          for (int i = 0; i < jsonArrayiaTBatches.size(); i++) {
            IATBatch.validateJsonElement(jsonArrayiaTBatches.get(i));
          };
        }
      }
      // validate the required field `fileControl`
      FileControl.validateJsonElement(jsonObj.get("fileControl"));
      if (jsonObj.get("NotificationOfChange") != null && !jsonObj.get("NotificationOfChange").isJsonNull()) {
        JsonArray jsonArraynotificationOfChange = jsonObj.getAsJsonArray("NotificationOfChange");
        if (jsonArraynotificationOfChange != null) {
          // ensure the json data is an array
          if (!jsonObj.get("NotificationOfChange").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `NotificationOfChange` to be an array in the JSON string but got `%s`", jsonObj.get("NotificationOfChange").toString()));
          }

          // validate the optional field `NotificationOfChange` (array)
          for (int i = 0; i < jsonArraynotificationOfChange.size(); i++) {
            Batch.validateJsonElement(jsonArraynotificationOfChange.get(i));
          };
        }
      }
      if (jsonObj.get("ReturnEntries") != null && !jsonObj.get("ReturnEntries").isJsonNull()) {
        JsonArray jsonArrayreturnEntries = jsonObj.getAsJsonArray("ReturnEntries");
        if (jsonArrayreturnEntries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ReturnEntries").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ReturnEntries` to be an array in the JSON string but got `%s`", jsonObj.get("ReturnEntries").toString()));
          }

          // validate the optional field `ReturnEntries` (array)
          for (int i = 0; i < jsonArrayreturnEntries.size(); i++) {
            Batch.validateJsonElement(jsonArrayreturnEntries.get(i));
          };
        }
      }
      // validate the optional field `fileADVControl`
      if (jsonObj.get("fileADVControl") != null && !jsonObj.get("fileADVControl").isJsonNull()) {
        ADVFileControl.validateJsonElement(jsonObj.get("fileADVControl"));
      }
      // validate the optional field `validateOpts`
      if (jsonObj.get("validateOpts") != null && !jsonObj.get("validateOpts").isJsonNull()) {
        ValidateOpts.validateJsonElement(jsonObj.get("validateOpts"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelFile.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelFile>() {
           @Override
           public void write(JsonWriter out, ModelFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelFile read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ModelFile given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModelFile
   * @throws IOException if the JSON string is invalid with respect to ModelFile
   */
  public static ModelFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelFile.class);
  }

  /**
   * Convert an instance of ModelFile to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

