/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mifos.ach.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.mifos.ach.model.ModelFile;
import org.mifos.ach.model.ValidateOpts;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mifos.ach.JSON;

/**
 * SegmentFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T08:19:26.833252621Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class SegmentFile {
  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  @javax.annotation.Nullable
  private ModelFile _file;

  public static final String SERIALIZED_NAME_OPTS = "opts";
  @SerializedName(SERIALIZED_NAME_OPTS)
  @javax.annotation.Nullable
  private Object opts = null;

  public static final String SERIALIZED_NAME_VALIDATE_OPTS = "validateOpts";
  @SerializedName(SERIALIZED_NAME_VALIDATE_OPTS)
  @javax.annotation.Nullable
  private ValidateOpts validateOpts;

  public SegmentFile() {
  }

  public SegmentFile _file(@javax.annotation.Nullable ModelFile _file) {
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nullable
  public ModelFile getFile() {
    return _file;
  }

  public void setFile(@javax.annotation.Nullable ModelFile _file) {
    this._file = _file;
  }


  public SegmentFile opts(@javax.annotation.Nullable Object opts) {
    this.opts = opts;
    return this;
  }

  /**
   * Get opts
   * @return opts
   */
  @javax.annotation.Nullable
  public Object getOpts() {
    return opts;
  }

  public void setOpts(@javax.annotation.Nullable Object opts) {
    this.opts = opts;
  }


  public SegmentFile validateOpts(@javax.annotation.Nullable ValidateOpts validateOpts) {
    this.validateOpts = validateOpts;
    return this;
  }

  /**
   * Get validateOpts
   * @return validateOpts
   */
  @javax.annotation.Nullable
  public ValidateOpts getValidateOpts() {
    return validateOpts;
  }

  public void setValidateOpts(@javax.annotation.Nullable ValidateOpts validateOpts) {
    this.validateOpts = validateOpts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentFile segmentFile = (SegmentFile) o;
    return Objects.equals(this._file, segmentFile._file) &&
        Objects.equals(this.opts, segmentFile.opts) &&
        Objects.equals(this.validateOpts, segmentFile.validateOpts);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(_file, opts, validateOpts);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentFile {\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    opts: ").append(toIndentedString(opts)).append("\n");
    sb.append("    validateOpts: ").append(toIndentedString(validateOpts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("file", "opts", "validateOpts"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SegmentFile
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SegmentFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SegmentFile is not found in the empty JSON string", SegmentFile.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SegmentFile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SegmentFile` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `file`
      if (jsonObj.get("file") != null && !jsonObj.get("file").isJsonNull()) {
        ModelFile.validateJsonElement(jsonObj.get("file"));
      }
      // validate the optional field `validateOpts`
      if (jsonObj.get("validateOpts") != null && !jsonObj.get("validateOpts").isJsonNull()) {
        ValidateOpts.validateJsonElement(jsonObj.get("validateOpts"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SegmentFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SegmentFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SegmentFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SegmentFile.class));

       return (TypeAdapter<T>) new TypeAdapter<SegmentFile>() {
           @Override
           public void write(JsonWriter out, SegmentFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SegmentFile read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SegmentFile given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SegmentFile
   * @throws IOException if the JSON string is invalid with respect to SegmentFile
   */
  public static SegmentFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SegmentFile.class);
  }

  /**
   * Convert an instance of SegmentFile to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

